### ISSUE TITLE
FileNotFoundException: minecraft\mappings\packages.csv

### ISSUE THREAD

**Issue by HoBoS-TaCo** [AbrarSyed/GMCP#11]
Error log:
https://gist.github.com/HoBoS-TaCo/6228412
Gradle build:
https://gist.github.com/HoBoS-TaCo/6228417

The file is there however it throws this error.

**Comment by AbrarSyed** [comment]
so the file EXISTS, but it dies anyways?? wut???
did you try again?
are you running linux?

**Comment by HoBoS-TaCo** [comment]
Yeah it's in the directory.

When I re-ran gradle build https://gist.github.com/HoBoS-TaCo/6228438

I'm using Windows.

**Comment by AbrarSyed** [comment]
i.. have no idea...
nor can I reproduce...

**Comment by AbrarSyed** [comment]
should be fixed. see #15 
try again with GMCP 0.8 or 0.8.2
