### ISSUE TITLE
Out Of Memory error & fix.

### ISSUE THREAD

**Issue by joshuacoles** [AbrarSyed/GMCP#13]
When running the assemble task in Gradle I ran across an [error](http://pastebin.com/HctSnjye).

If you add a gradle.properties setting the JVM args to:

```
 -Xmx256.
```

However since I am new to github I accidentally edited the wiki thinking it would fork it then pull request it.

Also the astyle fix does not seem to have worked. getting permission denied.

Thanks, 

Joshua

**Comment by AbrarSyed** [comment]
noted

the astyle thing will not be an issue for very long, as it is bieng replaced with JAstyle (see my repo).

about the OutofMemory thing.. uh..  I want to say thats an isolated case, and that for some people it may be a problem, while for others, the system might allocate enough on its own.

**Comment by joshuacoles** [comment]
Ok, thanks for the quick reply and sorry for editing the wiki.
