### ISSUE TITLE
compileMinecraftJava failing on linux

### ISSUE THREAD

**Issue by CaptainShadows** [AbrarSyed/GMCP#14]
http://pastebin.com/ycVYkLCs on a entirely clean and new workspace with the latest 0.7.4-SNAPSHOT as of now

**Comment by CaptainShadows** [comment]
Felt like it needed it's issue :P

**Comment by azenla** [comment]
This is a work in progress, no worries.

**Comment by AbrarSyed** [comment]
see #15
