### ISSUE TITLE
Crash while decompiling minecraft on linux

### ISSUE THREAD

**Issue by jeffreykog** [AbrarSyed/GMCP#15]
I tried to set GMCP up on an Ubuntu 12.04 system in jenkins. While decompiling minecraft, it crashed with the following error http://hastebin.reening.nl/dasukoriwa.txt

I use GMCP 0.7.3, link to the build.gradle file: https://github.com/jk-5/SuperPowers/blob/master/build.gradle

If there's any more information i have to provide, tell me

Update:
After looking into it more, it seems that the astyle executable is missing from minecraft/misc where it is normally. Shouldn't this be downloaded automaticly?

**Comment by CaptainShadows** [comment]
Test with 7.4-SNAPSHOT and check if the same thing happens, it not working on Linux is a known bug though

**Comment by jeffreykog** [comment]
Where? its not on mavencentral

**Comment by CaptainShadows** [comment]
Look for Wxample-Mod in my github and get the url from it's build.gradle ... I'm on my phone and it doesn't let me copy paste

**Comment by CaptainShadows** [comment]
Example-Mod ... stupid autocorrect

**Comment by jeffreykog** [comment]
Well. That version does not work too. I will try to collect an proper log from it and post it.

**Comment by AbrarSyed** [comment]
I know what the issue is, and how to fix it. Im working on it.

**Comment by AbrarSyed** [comment]
fixed. its up on MavenCentral now as GMCP 0.8
you should wait a bit though.. 0.8.1 will be up in 2 hours.

**Comment by jeffreykog** [comment]
Cool! Thanks!
