### ISSUE TITLE
Downloading Assets

### ISSUE THREAD

**Issue by HoBoS-TaCo** [AbrarSyed/GMCP#16]
If I understand GMCP correctly, it will have the minecraft decompiler as well as the build function. If this is the case would it be possible to select an assets folder to use on the client instead of redownloading them every time the environment is set up as the stage takes a long time for me with my terrible internet.

**Comment by AbrarSyed** [comment]
I can't check .minecraft folder or something.. but I am doing something similar. Assets are synced to ~/.gradle/caches/minecraft/assets
If you want to save time, you can copy your assets from the client minecraft folder to there. Just like the Minecraft folder, these will be synced. However it is also noteable that it will not be synced every build, but instead every time you run the setupWorkspace task.

**Comment by HoBoS-TaCo** [comment]
Great, thanks.

**Comment by yuuka-miya** [comment]
You can't check the .minecraft folder directly?

**Comment by AbrarSyed** [comment]
I technically can.. but its not gonna work well cross-platform.. and well.. its not worth the effort.

**Comment by yuuka-miya** [comment]
https://github.com/ForgeEssentials/FEInstaller/blob/master/src/main/java/com/ForgeEssentials/installer/GuiMain.java#L180
Windows, mac, unix.
