### ISSUE TITLE
Adding support for external Access Transformers

### ISSUE THREAD

**Issue by CaptainShadows** [AbrarSyed/GMCP#2]
... I needs it to build :P

**Comment by AbrarSyed** [comment]
simple.

```
minecraft {
    accessTransformers += 'path to transformer'
    accessTransformers += file('path to transformer')
    accessTransformers += { ... } // closure that evaluates to path to transformer
}
```

good thing you reminded me though.. I found a bug that would stop this from working. Il let you know when thats fixed. However, it won't change the way you configure it.

**Comment by CaptainShadows** [comment]
Kk thanks for that :-)

Btw how do I add a .jar into the mcp/lib folder?

**Comment by AbrarSyed** [comment]
what do you mean?

**Comment by CaptainShadows** [comment]
How do I add the src of one of my mods to the lib folder so another mod can use it ( AKA how to add a dependency )

**Comment by AbrarSyed** [comment]
http://www.gradle.org/docs/current/userguide/dependency_management.html#sub:file_dependencies

**Comment by CaptainShadows** [comment]
Better said the build and deobf version of the jar

**Comment by CaptainShadows** [comment]
K thanks will look at it when im no longer in my cell :-P
