### ISSUE TITLE
Minecraft on mac does not work with java 1.7.

### ISSUE THREAD

**Issue by joshuacoles** [AbrarSyed/GMCP#20]
When trying to get gmcp to work it fails with:

FAILURE: Build failed with an exception.
- Where:
  Build file '/Users/joshuacoles/Downloads/SecretRoomsMod-forge-master 2/build.gradle' line: 13
- What went wrong:
  A problem occurred evaluating root project 'SecretRoomsMod-forge-master 2'.
  
  > com/github/abrarsyed/gmcp/tasks/CachedTask : Unsupported major.minor version 51.0
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

This is because I have java 6 which is required for Minecraft and so I cant run it and if i could it would not properly work with lwjgl errors. Is there a say this could be Java 6 compatible.

This is because I have java 6, java 7 causes problems with lwjgl. Is there any way this could be made java 6 compatible the commit that changed it is:
https://github.com/AbrarSyed/GMCP/commit/a2b88d087244fe8771972e3c34b90a4ab849affe.

Link to the java 7 mac discussion is:
http://www.minecraftforum.net/topic/1954605-162-mac-osx-latest-java-osx-update-causing-minecraft-to-hang-and-crash/.

Joshua

PS sorry for posting without content miss clicked enter.

**Comment by jeffreykog** [comment]
How does it not work? Does it crash? Are there any errors?
Provide more information and logs. This issue is useless as it is now

**Comment by joshuacoles** [comment]
Sorry editing now.

**Comment by joshuacoles** [comment]
Git derp...

**Comment by jeffreykog** [comment]
> com/github/abrarsyed/gmcp/tasks/CachedTask : Unsupported major.minor version 51.0

This means that you try to run java 7 code with java 6. That's your problem

**Comment by joshuacoles** [comment]
I know but minecraft on mac does not work with 7

**Comment by jeffreykog** [comment]
Also, i have a mac, i'm trying how it does for me

**Comment by joshuacoles** [comment]
Ok thanks

**Comment by jeffreykog** [comment]
GMCP 0.8.1 with forge build 961 for mc 1.6.4 works fine for me!

**Comment by joshuacoles** [comment]
Oh you managed to get java 7 working with mc tried about 2 months ago didn't work.

**Comment by jeffreykog** [comment]
No. Minecraft has to run on java 6, but you can use GMCP with java 7. Have you even tried it?

**Comment by joshuacoles** [comment]
But wont mc complain when compiling and the mods require java 7 to work?

**Comment by joshuacoles** [comment]
Checking with vm now.

**Comment by jeffreykog** [comment]
Why? You don't run minecraft while decompiling...
Test before you report.

**Comment by joshuacoles** [comment]
Oh ok sorry to waste your time, have a good day.

**Comment by jeffreykog** [comment]
You didn't waste my time, else i wouldn't comment on this ;) Have a nice day too!

**Comment by joshuacoles** [comment]
Ok :-)

**Comment by AbrarSyed** [comment]
I love how I didn't even have to reply
