### ISSUE TITLE
exception on java 6

### ISSUE THREAD

**Issue by piotrb** [AbrarSyed/GMCP#21]
See gist: https://gist.github.com/piotrb/e2c9432a5e302aa8fe4f

Seems to crash very early on in the build running on Apple's default JDK

java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-462-11M4609)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-462, mixed mode)

---

Confirmed to be fine running on Sun's latest java after upgrading.

**Comment by M3gaFr3ak** [comment]
java 7 introduces names groups. @AbrarSyed you should use this (is it a) library(?):

https://code.google.com/p/named-regexp

this one accepts named groups  in java 6 (named group was the [sdsds]+ thing i think) or so :P

here's a giothub fork including a compiled jar, probably easier for you:

https://github.com/tony19/named-regexp

**Comment by AbrarSyed** [comment]
fixed, itl be up as version 0.8.5 reall realy soon, like in 40 min soon.

**Comment by M3gaFr3ak** [comment]
thanks :D the people on my thread will be happy, me too. and themattabase .D
