### ISSUE TITLE
GMCP Clean error.

### ISSUE THREAD

**Issue by Fred4106** [AbrarSyed/GMCP#22]
After copying resource files that get tokens replaced, the next build fails to override them with updated versions.  This causes problems with version numbers and similar.

**Comment by CaptainShadows** [comment]
could you link your `build.gradle`?

**Comment by Fred4106** [comment]
https://bitbucket.org/Fred4106/red-pipes/src/5dd2dd0179b8b16ef4ef8386cd2ff38f3aa72ea6/build.gradle?at=master

**Comment by AbrarSyed** [comment]
hmmm, not sure if this is fixable.. il do some research and find out if its possible to do anything about this.. it IS a legit problem though...

**Comment by Tiim** [comment]
I included the folowing line in my build script and it works so far.

```
processResources.outputs.upToDateWhen{ false }
```

I found this solution here: http://stackoverflow.com/questions/8098591/how-can-i-ensure-that-the-processresources-task-of-a-gradle-build-always-runs

**Comment by Fred4106** [comment]
In case anyone else comes across this, Tiim's change fixed the problem. Thanks
