### ISSUE TITLE
jAstyle 

### ISSUE THREAD

**Issue by M3gaFr3ak** [AbrarSyed/GMCP#25]
I can't compile this until jAstyle on maven central is compiled on java 6 :(
jAstyle has as java version version 7, so i cant compile gmcp with it...

**Comment by jeffreykog** [comment]
Or you just install java 7..
http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html
There are builds for all popular operating systems on there.

**Comment by M3gaFr3ak** [comment]
yeah,  but i gotta stay compatible with stupid mac users.....

**Comment by jeffreykog** [comment]
There is java 7 for mac. After installing that, you can still use JDK 6 and 7. I see no problem there

**Comment by jeffreykog** [comment]
Also. You can use java 7 to build and target java 6. It will be compatible with mac users, and with GMCP. I'd say double profit there

**Comment by M3gaFr3ak** [comment]
i thought java 7 was only supported after a certain version of macosx? people  in minecraftforums complaining all the wayM)

**Comment by jeffreykog** [comment]
There are official java 7 builds on java.net. Is supported along all versions as far as i know. As i said, you can tell the buildscript to target 1.6. It will create 1.6 classes, even tough you are using a 1.7 jdk.
I can test this on my fathers apple pc next weekend if you want to be safe.

**Comment by AbrarSyed** [comment]
fixed. its going to be up on central really soon.
