### ISSUE TITLE
Mods built in GMCP fail to work on mac

### ISSUE THREAD

**Issue by TuxCraft** [AbrarSyed/GMCP#30]
I recently installed GMCP and tried building my mod with it. Works really well except when I put it in the mine craft mods folder it crashes soon after startup, here is the crash http://pastebin.com/q0J5wYL8. Something similar also happened with the built version of Dream Dimension after mod jam. 

Other people who I have asked to test have had no problems running it so I believe the issue is because I am working on a mac.

**Comment by AbrarSyed** [comment]
Thats the mod bieng compiled for 1.7, and you running 1.6

**Comment by GUIpsp** [comment]
@AbrarSyed maybe that should be forced

**Comment by AbrarSyed** [comment]
I guess il set it by default to 1.6 or something...
but it doesnt matter anymore.. ForgeGradle is scheduled for release like tomorrow

**Comment by M3gaFr3ak** [comment]
forgr gradle for 1.6 x?

**Comment by GUIpsp** [comment]
@M3gaFr3ak yes.

**Comment by M3gaFr3ak** [comment]
yay :D

**Comment by M3gaFr3ak** [comment]
where did it release?

**Comment by HoBoS-TaCo** [comment]
@M3gaFr3ak It hasn't yet.

**Comment by CaptainShadows** [comment]
Can someone explain what that is though? ..... I haven't been paying attention :-(

**Comment by yuuka-miya** [comment]
@CaptainShadows "wherefore art thou forgegradle"

**Comment by TuxCraft** [comment]
I also had this problem with Dream Dimension where you correctly compiled it. I updated java to 1.7 like you mentioned in team speak, but I am still getting crashes with a similar log http://pastebin.com/MZfiEVbq (easiest instance to test on since I had the folder open, sorry for the extra mods :P). 

Both of these mods were compiled in an older version of gmcp so I am not sure if this bug is fixed or not.

**Comment by AbrarSyed** [comment]
try ForgeGradle...
