### ISSUE TITLE
astyle doesm't have the permissions it needs for OS X.

### ISSUE THREAD

**Issue by keplersj** [AbrarSyed/GMCP#5]
astyle needs to be chmoded with executable permissions for OS X builds to work.

**Comment by AbrarSyed** [comment]
I don't have a mac, and have no way to test if problem. Is it possible for
you to send a PR fixing this? the astyle exectureable can be found in
src/resources/astyle

**Comment by keplersj** [comment]
Yeah. I should be able to. I'll probably have one soon.
—
