### ISSUE TITLE
Error patching

### ISSUE THREAD

**Issue by CaptainShadows** [AbrarSyed/GMCP#7]
http://goo.gl/8mAKyp

I get that when I try to build with GMCP on Dries' Jenkins
(Nucleum-Omnium if you want to check)

**Comment by azenla** [comment]
https://gist.github.com/kaendfinger/6215561

**Comment by azenla** [comment]
Version mismatches could be the problem. investigating.

**Comment by azenla** [comment]
Fixed by using Java based patching tool

**Comment by AbrarSyed** [comment]
which is currently in the 0.7.4 snapshot...

**Comment by azenla** [comment]
Has this been fixed?

**Comment by CaptainShadows** [comment]
I guess so :P
