### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by dariusc93** [AbrarSyed/GMCP#8]
Even though I tried to adjust the settings, it seems to be getting that exception while running on Ubuntu 13.04.

**Comment by AbrarSyed** [comment]
noted... not sure why this is happenning though....

**Comment by azenla** [comment]
Requires you to set your Files Open Limit higher: http://posidev.com/blog/2009/06/04/set-ulimit-parameters-on-ubuntu/

**Comment by dariusc93** [comment]
i followed that before but still had the same issue. It was said to be with fernflower but ill try on linux mint and see how that works

**Comment by dariusc93** [comment]
had to manually edit the files to get it working
